# Generated by Django 3.2 on 2024-06-06 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_usermodel_role'),
        ('users', '0002_auto_20240605_2303'),
    ]

    operations = [
    ]
