# Generated by Django 3.2 on 2024-06-07 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_auto_20240606_1616'),
        ('reviews', '0004_auto_20240606_1722'),
    ]

    operations = [
    ]
