# Generated by Django 3.2 on 2024-06-07 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_merge_0004_auto_20240606_1616_0004_auto_20240606_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(null=True, through='reviews.GenreTitle', to='reviews.Genre', verbose_name='Жанр'),
        ),
    ]
